lastupdatecheck: 0
recentrepos:
    - /home/time/workspace/dotifiles
    - /home/time/文档/Notes
    - /home/time/workspace/blog
    - /home/time/workspace/st
    - /home/time/workspace/dwm
    - /home/time/.local/share/nvim/lazy/LuaSnip
    - /home/time/workspace/wudao-dict
    - /home/time/scripts
    - /home/time/.config/omz
    - /home/time/.local/share/fcitx5/rime
startuppopupversion: 5
lastversion: 0.42.0
customcommandshistory:
    - q
    - wq
    - ""
    - help
    - git prune
hidecommandlog: false
ignorewhitespaceindiffview: false
diffcontextsize: 3
localbranchsortorder: recency
remotebranchsortorder: alphabetical
gitlogorder: topo-order
gitlogshowgraph: always
