lastupdatecheck: 0
recentrepos:
- /home/time/workspace/dotifiles
- /home/time/.config/omz
- /home/time/workspace/dwm
- /home/time/scripts
- /home/time/thesis/ResearchSubject
- /home/time/.local/share/fcitx5/rime
- /home/time/Pictures/wallpaper
startuppopupversion: 5
customcommandshistory:
- ""
- help
- q
- git prune
hidecommandlog: false
ignorewhitespaceindiffview: false
