lastupdatecheck: 0
recentrepos:
    - /home/time/workspace/dotifiles
    - /home/time/workspace/dotifiles/config/nvim
    - /home/time/.config/nvim
    - /home/time/scripts
    - /home/time/workspace/blog
    - /home/time/workspace/st
    - /home/time/文档/Notes
    - /home/time/picom
    - /home/time/workspace/dwm
    - /home/time/.local/share/nvim/lazy/LuaSnip
    - /home/time/workspace/wudao-dict
    - /home/time/.config/omz
    - /home/time/.local/share/fcitx5/rime
startuppopupversion: 5
didshowhunkstaginghint: false
lastversion: 0.54.0
customcommandshistory:
    - q
    - ""
    - wq
    - help
    - git prune
hidecommandlog: false
